2024-09-19 13:49:30,859 - SimulatorRunner - INFO - Create the Simulator Server.
2024-09-19 13:49:30,861 - CoreCell - INFO - server: creating listener on tcp://0:38361
2024-09-19 13:49:30,888 - CoreCell - INFO - server: created backbone external listener for tcp://0:38361
2024-09-19 13:49:30,888 - ConnectorManager - INFO - 31734: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2024-09-19 13:49:30,889 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:28298] is starting
2024-09-19 13:49:31,390 - CoreCell - INFO - server: created backbone internal listener for tcp://localhost:28298
2024-09-19 13:49:31,391 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE tcp://0:38361] is starting
2024-09-19 13:49:31,477 - nvflare.fuel.hci.server.hci - INFO - Starting Admin Server localhost on Port 60719
2024-09-19 13:49:31,477 - SimulatorRunner - INFO - Deploy the Apps.
2024-09-19 13:49:31,483 - SimulatorRunner - INFO - Create the simulate clients.
2024-09-19 13:49:31,489 - ClientManager - INFO - Client: New client site-1@192.168.0.105 joined. Sent token: 4d0666d8-3fb7-4ad7-8a89-3f2a52ecfc34.  Total clients: 1
2024-09-19 13:49:31,489 - FederatedClient - INFO - Successfully registered client:site-1 for project simulator_server. Token:4d0666d8-3fb7-4ad7-8a89-3f2a52ecfc34 SSID:
2024-09-19 13:49:31,491 - ClientManager - INFO - Client: New client site-2@192.168.0.105 joined. Sent token: 6437b3b3-4ad7-4dc8-8086-ca5588155df6.  Total clients: 2
2024-09-19 13:49:31,491 - FederatedClient - INFO - Successfully registered client:site-2 for project simulator_server. Token:6437b3b3-4ad7-4dc8-8086-ca5588155df6 SSID:
2024-09-19 13:49:31,491 - SimulatorRunner - INFO - Set the client status ready.
2024-09-19 13:49:31,491 - SimulatorRunner - INFO - Deploy and start the Server App.
2024-09-19 13:49:31,494 - Cell - INFO - Register blob CB for channel='server_command', topic='*'
2024-09-19 13:49:31,494 - Cell - INFO - Register blob CB for channel='aux_communication', topic='*'
2024-09-19 13:49:31,494 - ServerCommandAgent - INFO - ServerCommandAgent cell register_request_cb: server.simulate_job
2024-09-19 13:49:33,626 - JsonScanner - ERROR - Traceback (most recent call last):
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/json_scanner.py", line 99, in _do_scan
    node.processor.process_element(node)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 150, in process_element
    self.process_config_element(self.config_ctx, node)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/fed/server/server_json_config.py", line 134, in process_config_element
    controller = self.authorize_and_build_component(element, config_ctx, node)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 103, in authorize_and_build_component
    return self.build_component(config_dict)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/fed/server/server_json_config.py", line 166, in build_component
    t = super().build_component(config_dict)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/component_builder.py", line 86, in build_component
    return instantiate_class(class_path, class_args)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/class_utils.py", line 54, in instantiate_class
    c = get_class(class_path)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/class_utils.py", line 33, in get_class
    module_ = importlib.import_module(module_name)
  File "/home/mohamed/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/mohamed/3563bb56-889a-4bad-a486-da7f2f0b6a03/MyGithub/Coinstac_all/MeshDist_nvflare/app/code/workflow/gradient_aggregation_workflow.py", line 1, in <module>
    from nvflare.apis.impl.controller import Controller, Task, ClientTask
ImportError: cannot import name 'ClientTask' from 'nvflare.apis.impl.controller' (/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/apis/impl/controller.py)

2024-09-19 13:49:33,627 - SimulatorRunner - ERROR - FL server execution exception: ConfigError: Error processing '/media/mohamed/3563bb56-889a-4bad-a486-da7f2f0b6a03/MyGithub/Coinstac_all/MeshDist_nvflare/simulator_workspace/server/simulate_job/app_server/config/config_fed_server.json' in element '{"id": "gradient_aggregation_workflow", "path": "workflow.gradient_aggregation_workflow.GradientAggregationWorkflow", "args": {"aggregator_id": "gradient_aggregator"}}': path: 'workflows.#1', exception: 'ImportError: cannot import name 'ClientTask' from 'nvflare.apis.impl.controller' (/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/apis/impl/controller.py)'
Traceback (most recent call last):
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/json_scanner.py", line 99, in _do_scan
    node.processor.process_element(node)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 150, in process_element
    self.process_config_element(self.config_ctx, node)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/fed/server/server_json_config.py", line 134, in process_config_element
    controller = self.authorize_and_build_component(element, config_ctx, node)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 103, in authorize_and_build_component
    return self.build_component(config_dict)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/fed/server/server_json_config.py", line 166, in build_component
    t = super().build_component(config_dict)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/component_builder.py", line 86, in build_component
    return instantiate_class(class_path, class_args)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/class_utils.py", line 54, in instantiate_class
    c = get_class(class_path)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/class_utils.py", line 33, in get_class
    module_ = importlib.import_module(module_name)
  File "/home/mohamed/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/mohamed/3563bb56-889a-4bad-a486-da7f2f0b6a03/MyGithub/Coinstac_all/MeshDist_nvflare/app/code/workflow/gradient_aggregation_workflow.py", line 1, in <module>
    from nvflare.apis.impl.controller import Controller, Task, ClientTask
ImportError: cannot import name 'ClientTask' from 'nvflare.apis.impl.controller' (/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/apis/impl/controller.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/fed/server/server_app_runner.py", line 76, in start_server_app
    conf.configure()
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 147, in configure
    raise e
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 144, in configure
    self._do_configure()
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 137, in _do_configure
    self.json_scanner.scan(self)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/json_scanner.py", line 159, in scan
    self._do_scan(node)
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/json_scanner.py", line 129, in _do_scan
    self._do_scan(_child_node(node, k, 0, v))
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/json_scanner.py", line 132, in _do_scan
    self._do_scan(_child_node(node, node.key, i + 1, element[i]))
  File "/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/fuel/utils/json_scanner.py", line 121, in _do_scan
    raise ConfigError(self.get_process_err_msg(e, elmt_str, location, node))
nvflare.fuel.common.excepts.ConfigError: Error processing '/media/mohamed/3563bb56-889a-4bad-a486-da7f2f0b6a03/MyGithub/Coinstac_all/MeshDist_nvflare/simulator_workspace/server/simulate_job/app_server/config/config_fed_server.json' in element '{"id": "gradient_aggregation_workflow", "path": "workflow.gradient_aggregation_workflow.GradientAggregationWorkflow", "args": {"aggregator_id": "gradient_aggregator"}}': path: 'workflows.#1', exception: 'ImportError: cannot import name 'ClientTask' from 'nvflare.apis.impl.controller' (/home/mohamed/anaconda3/lib/python3.8/site-packages/nvflare/apis/impl/controller.py)'
2024-09-19 13:49:33,627 - SimulatorServer - INFO - Server app stopped.


2024-09-19 13:49:34,499 - SimulatorRunner - ERROR - Simulator run error: RuntimeError: Could not start the Server App.
2024-09-19 13:49:38,429 - MPM - INFO - MPM: Good Bye!
